baseURL = "https://pdcconf.in"
languageCode = "en"
title = "PowerShell DevOps and Cloud Conference 2021"

# Theme
theme = "devfest-theme-hugo"

# Params

enableEmoji = true
enableRobotsTXT = true
enableMissingTranslationPlaceholders = true
relativeURLs = true
googleAnalytics = "UA-37717223-8"

[params]
    siteURL = "www.pdcconf.in"
    title = "PowerShell DevOps and Cloud Conference 2021"
    date = "2021-09-15"
    description = "PDC Conference description here"
    images = ["/images/social-share.jpg"]
    email = "info@pdcconf.in"
    keywords = "event, gdg, gde, devfest, google, programming, android, chrome, developers, web, cloud, androiddev"
    copyright = "We :heart:️ chocolatines"
    cfpUrl = "sessionize url here"
    regsitrationUrl = "https://www.eventbrite.com/e/powershell-devops-and-cloud-conference-2021-tickets-164643185199"
    cfpSessionizeUrl = "https://sessionize.com/powershell-devops-and-cloud-conference"
    virtualBoothUrl = "https://teams.microsoft.com/l/meetup-join/19%3ameeting_MDU1ZmVmNGQtYzY5Yi00ZGVmLTllNjgtM2ZjMzZhZDU0Nzlk%40thread.v2/0?context=%7b%22Tid%22%3a%22645f4842-9ffb-4493-bab9-5246f05bb886%22%2c%22Oid%22%3a%222e8071b7-4a59-4efb-a642-31bcc36512cd%22%7d"
    socialMediaShareText = "PDCConf 2021 is Announced, I'm excited. Check more details here: www.pdcconf.in"
    linkedInURL = "https://www.linkedin.com/company/pdcconf/"
    facebookPageURL = "https://www.facebook.com/pdcconf/"
    twitterPageURL = "https://twitter.com/pdcconf"
    appleTouchIcon = "/apple-touch-icon.png"
    favicon32 = "/favicon-32x32.png"
    favicon16 = "/favicon-16x16.png"
    manifest = "/manifest.json"
    themeColor = "#673ab7"
    googleWebmasterKey = "BcIJYWDHoblML5DO66_b1BGBne9J_7Oq3GjC5SDCKK8"

[params.logos]
    jumbo = "/images/logos/PDCConf_transparent.png"
    header = "/images/logos/PDCConf_transparent_logo.png"
    footer = "/images/logos/PDCConf_transparent_logo.png"
    booth = "/images/partners/cloudlabsai-booth.png"

[menu]


[languages]
[languages.en]
    weight = 1
    languageName = "gb"

[taxonomies]
  tag = "tags"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = true
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = true
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false
